server:
  port: 8090
spring:
  application:
    name: "Bootcam"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: "localhost"
    port: "5434"
    database: "bootcamp"
    schema: "public"
    username: "postgres"
    password: "postgres"
routers:
  paths:
    bootcamp: "/api/v1/bootcamp"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

